lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app


app_name = "lab_1"

urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_7/urls.py
from django.conf.urls import url
from .views import index, add_friend, validate_npm, delete_friend, friend_list, my_friend_list, view

app_name = "lab_7"

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add-friend/$', add_friend, name='add-friend'),
    url(r'^validate-npm/$', validate_npm, name='validate-npm'),
    url(r'^get-friend-list/delete-friend/(?P<friend_id>[0-9]+)/$', delete_friend, name='delete-friend'),
    url(r'^get-friend-list/$', friend_list, name='get-friend-list'),
    url(r'^my-list-friend/$', my_friend_list, name='my-friend-list'),
    url(r'^get-friend-list/view/(?P<friend_id>[0-9]+)/$', view, name='view'),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_2_addon.urls as lab_2_addon
from lab_1.views import index as index_lab1
from django.views.generic.base import RedirectView
import lab_3.urls as lab_3
import lab_4.urls as lab_4
import lab_5.urls as lab_5
import lab_6.urls as lab_6
import lab_7.urls as lab_7
import lab_8.urls as lab_8
import lab_9.urls as lab_9
import lab_10.urls as lab_10
import resume.urls as resume

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-2-addon/', include(lab_2_addon,namespace='lab-2-addon')),
    url(r'^lab-1/', include(lab_1,namespace='lab-1')),
    url(r'^lab-2/', include(lab_2,namespace='lab-2')),
    url(r'^lab-3/', include(lab_3,namespace='lab-3')),
    url(r'^lab-4/', include(lab_4,namespace='lab-4')),
    url(r'^lab-5/', include(lab_5, namespace='lab-5')),
    url(r'^lab-6/', include(lab_6,namespace='lab-6')),
    url(r'^lab-7/', include(lab_7, namespace='lab-7')),
    url(r'^lab-8/', include(lab_8, namespace='lab-8')),
    url(r'^lab-9/', include(lab_9, namespace='lab-9')),
    url(r'^lab-10/', include(lab_10, namespace='lab-10')),
    url(r'^resume/', include(resume, namespace='resume')),
    url(r'^$', RedirectView.as_view(url="/resume/",permanent="true"), name='index'),
]

lab_7/models.py
from django.db import models

class Friend(models.Model):
    friend_name = models.CharField(max_length=400)
    npm = models.CharField(max_length=250)
    alamat_mhs = models.CharField(max_length=400,default="-")
    tgl_lahir= models.CharField(max_length=100,default="-")
    prodi = models.CharField(max_length=100, default="-")
    angkatan = models.CharField(max_length=100, default="-")
    added_at = models.DateField(auto_now_add=True)

lab_7/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Friend
from .api_csui_helper.csui_helper import CSUIhelper
import os
import json

response = {}
csui_helper = CSUIhelper()

def index(request):
    # Page halaman menampilkan list mahasiswa yang ada
    # TODO berikan akses token dari backend dengan menggunakaan helper yang ada

    mahasiswa_list = csui_helper.instance.get_mahasiswa_list()
    paginator = Paginator(mahasiswa_list,15)
    friend_list = Friend.objects.all()
    auth = csui_helper.instance.get_auth_param_dict()
    print(auth['access_token'])
    print(auth['client_id'])
    response = {
                "mahasiswa_list": mahasiswa_list, 
                "friend_list": friend_list,
                "auth":auth,
                }
    html = 'lab_7/lab_7.html'
    page = request.GET.get('page', 1) if int(request.GET.get('page', 1)) > 0 and int(request.GET.get('page', 1)) < 69 else 1
    
    #coba akses pagenya
    mhss = paginator.page(page)

    response['mhss']=mhss
    return render(request, html, response)

def friend_list(request):
    friend_list = Friend.objects.all()
    response['friend_list'] = friend_list
    html = 'lab_7/daftar_teman.html'
    return render(request, html, response)

@csrf_exempt
def add_friend(request):
    if request.method == 'POST':
        name = request.POST['name']
        npm = request.POST['npm']
        alamat_mhs = request.POST['alamat_mhs']
        tgl_lahir = request.POST['tgl_lahir']
        prodi = request.POST['prodi']
        angkatan = request.POST['angkatan']
        friend = Friend(friend_name=name, npm=npm, alamat_mhs=alamat_mhs, tgl_lahir=tgl_lahir, prodi=prodi, angkatan=angkatan)
        friend.save()
        data = model_to_dict(friend)
        return HttpResponse(data)

def delete_friend(request, friend_id):
    Friend.objects.filter(id=friend_id).delete()
    print("coba")
    return redirect('/lab-7/get-friend-list/')

@csrf_exempt
def validate_npm(request):
    if request.method == 'POST':
        npm = request.POST.get('npm', None)
        data = {
            'is_taken': Friend.objects.filter(npm=npm).exists()
        }
        return JsonResponse(data)

def model_to_dict(obj):
    data = serializers.serialize('json', [obj,])
    struct = json.loads(data)
    data = json.dumps(struct[0]["fields"])
    return data

def my_friend_list(request):
    friend_list = Friend.objects.all()
    data= serializers.serialize("json", friend_list)  
    return HttpResponse(data)

def view(request, friend_id):
    print("npm",friend_id)
    print(Friend.objects.filter(id=friend_id))
    friend = Friend.objects.filter(id=friend_id)[0]
    response['friend']=friend
    html = 'lab_7/view.html'
    return render(request, html, response)

lab_7/templates/lab_7/daftar_teman.html
{% extends "base.html" %}
{% load static %}
{% block title %}
My Friends
{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/lab_7.css' %}" />
{% endblock %}

{% block header %}
{% include 'partials/header.html' with headerlist_left='lab_7/partials/header.html' %}
{% endblock %}

{% block content %}

    <section name="friend-list" id="friend-list">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-lg-8">
                    <h2> Friend Fasilkom</h2>
                    <div id="friend-list" class="list-group">
                      
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block script %}
    <script>
        $( document ).ready(function () {
            {# lengkapi pemanggilan ajax berikut untuk mengambil daftar teman yang ada di database #}
            $.ajax({
                method: "GET",
                url: "{% url "lab-7:my-friend-list" %}",
                success: function (friend_list) {
                    console.log(friend_list);
                    objFriend = JSON.parse(friend_list);
                    console.log(objFriend.length);
                    if (objFriend.length==0){
                        console.log("masuk")
                        var html = '<div class="alert alert-danger text-center">'+
                            '<strong>Opps!</strong> Tidak ada teman'+
                        '</div>';
                        $('#friend-list').append(html);
                    }
                    $.each(objFriend, function(index, friend){
                        image = '<span class="float-xs-right">'+
                        '<img src="{% static "img/unfriend.png" %}" width="30" height="30" margin="0"'+ 
                        'onclick="delete_friend('+friend.pk+')">'+
                        '</img>'+
                        '</span>';
                        btnView = '<span class="btn btn-xs btn-default float-xs-right" onclick="view('+friend.pk+')">'+
                                    "View"+
                                    "</span>"
                        html = '<a class="list-group-item clearfix" style="margin:0px 80px 0 80px;">' +
                        friend.fields.friend_name + "("+friend.fields.npm+")"+image+btnView+
                        '</a>';
                        $("#friend-list").append(html)
                    })
                    
                },
                error: function(error){
                    alert("Anda tidak memiliki teman")
                }
            });
        });

        var delete_friend = function(id){
            console.log("delete"+id)
            window.open('delete-friend/'+id+'/', '_self')
        }

        var view = (pk)=>{
            console.log(pk)
            window.open('view/'+pk+'/','_self')
        }


    </script>
{% endblock %}

}

lab_7/templates/lab_7/lab_7.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
Fasilkom Friends
{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/lab_7.css' %}" />
{% endblock %}

{% block header %}
{% include 'partials/header.html' with headerlist_left='lab_7/partials/header.html' %}
{% endblock %}

{% block content %}
<section name="mahasiswa-list" id="mahasiswa-list">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-lg-8">
                <h2> Mahasiswa Fasilkom</h2>
                <div class="list-group">
                    {% if mahasiswa_list %}
                        {% for mahasiswa in mhss %}
                            <span class="list-group-item clearfix">
                                {{ mahasiswa.nama }} ({{ mahasiswa.npm }})
                                <span class="float-xs-right">
                                    <span class="btn btn-xs btn-outline-dark" onClick="addFriendFromList('{{ mahasiswa.nama }}', '{{ mahasiswa.npm }}',' {{mahasiswa.alamat_mhs}} ',' {{mahasiswa.tgl_lahir}} ','{{ mahasiswa.program.0.nm_org }}',' {{mahasiswa.program.0.angkatan}} ' )">
                                        Tambah sebagai teman
                                    </span>
                                </span>
                            </span>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada mahasiswa
                        </div>
                    {% endif %}
                </div>
                <div class="pagination" style="align-self:center">
                    <span class="step-links" >
                        {% if mhss.has_previous %}
                            <a type="button" class="btn btn-primary btn-sm" href="?page={{ mhss.previous_page_number }}">previous</a>
                        {% endif %}
                
                        <span class="current">
                            Page {{ mhss.number }} of {{ mhss.paginator.num_pages }}
                        </span>
                
                        {% if mhss.has_next %}
                            <a type="button" class="btn btn-primary btn-sm" href="?page={{ mhss.next_page_number }}">next</a>
                        {% endif %}
                    </span>
                </div>
                {% if auth %}
                    <div id="token" hidden="true">{{ auth.access_token }}</div>
                    <div id="cid" hidden="true">{{ auth.client_id }}</div>
                {% endif %}

            </div>

            <div class="col-md-4 col-lg-4">
                <h2> Teman Saya </h2>
                <div class="list-group" id="friend-list">
                    {% if friend_list %}
                        {% for friend in friend_list %}
                            <a class="list-group-item clearfix">
                                {{ friend.friend_name }} ({{ friend.npm }})
                            </a>
                        {% endfor %}
                        
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada teman
                        </div>
                    {% endif %}
                </div>
                <form id="add-friend" action="#">
                    {% csrf_token %}
                    <label for="field_npm">npm</label>
                    <input id="field_npm" type="text" name="npm" class="form-control"/>
                    <label for="field_name">name</label>
                    <input id="field_name" type="text" name="name" class="form-control"/>
                    <button type="submit">Tambah</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

...
{% block script %}

<script>
    var addFriendFromList = function(nama, npm, alamat_mhs, tgl_lahir, prodi, angkatan){
        $.ajax({
            method: "POST",
            url: '{% url "lab-7:validate-npm" %}',
            data: {
                'npm': npm,
                
            },
            dataType: 'json',
            beforeSend: function(xhr) {
                xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
            },
            success: function (data) {
                console.log(data)
                if (data.is_taken) {
                    alert("Mahasiswa dengan npm seperti ini sudah ada");
                }else{
                    addFriend(nama, npm, alamat_mhs, tgl_lahir, prodi, angkatan);
                }
            }
        });
    }

    var token = document.getElementById("token").innerHTML;
    var cid = document.getElementById("cid").innerHTML;

    // var cekAdd = (nama, npm, alamat_mhs, tgl_lahir, prodi, angkatan)=>{
    //     $.ajax({
    //         method: "POST",
    //         url: '{% url "lab-7:validate-npm" %}',
    //         data: {
    //             'npm': npm
    //         },
    //         dataType: 'json',
    //         success: function (data) {
    //             console.log(data)
    //             if (data.is_taken) {
    //                 alert("Mahasiswa dengan npm seperti ini sudah ada");
    //             }else{
    //                 addFriend(nama, npm, alamat_mhs, tgl_lahir, prodi, angkatan);
    //             }
    //         }
    //     });
    // }

    var addFriend = function(nama, npm, alamat_mhs, tgl_lahir, prodi, angkatan) {
        $.ajax({
            method: "POST",
            url: "{% url 'lab-7:add-friend' %}",
            data: { name: nama, npm: npm, alamat_mhs:alamat_mhs, tgl_lahir:tgl_lahir, prodi:prodi, angkatan:angkatan},
            beforeSend: function(xhr) {
                xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
            },
            success : function (data) {
                html = '<a class="list-group-item clearfix">' +
                     nama +" ("+ npm+")"+
                    '</a>';
                $("#friend-list").append(html)
            },
            error : function (error) {
                console.log(error)
                // alert("Mahasiswa tersebut sudah ditambahkan sebagai teman")
            }
        });
    };

    $("#add-friend").on("submit", function () {
        var npm = $("#field_npm").val();
        var corsProxy = 'https://cors-anywhere.herokuapp.com/';
        console.log(token)
        var obj = {'access_token' : token, 'client_id' : cid}
        var param = $.param(obj);
        $.ajax({
            method: "GET",
            url: corsProxy+'https://api-dev.cs.ui.ac.id/siakngcs/mahasiswa/'+npm+'/?'+param,
            success: function(data) {
                console.log(data)
                addFriend(data.nama, data.npm, data.alamat_mhs,
                          data.tgl_lahir,data.program[0].nm_org,data.program[0].angkatan
                )
            },
            error: function(error) {
                alert("\n\t\t\tNPM tidak valid:\n\n'Tidak ada mahasiswa dengan NPM tersebut'")
            }
        });
        event.preventDefault();
        $("#field_npm").val("");
        $("#field_name").val("");

    });

    $("#field_npm").change(function () {
        console.log( $(this).val() );
        npm = $(this).val();
        $.ajax({
            method: "POST",
            url: '{% url "lab-7:validate-npm" %}',
            data: {
                'npm': npm
            },
            dataType: 'json',
            success: function (data) {
                console.log(data)
                if (data.is_taken) {
                    alert("Mahasiswa dengan npm seperti ini sudah ada");
                }
            }
        });
    });
</script>
{% endblock %}

lab_7/templates/lab_7/view.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}
{{friend.friend_name}} Data
{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/lab_7.css' %}" />
{% endblock %}

{% block header %}
{% include 'partials/header.html' with headerlist_left='lab_7/partials/header.html' %}
{% endblock %}

{% block content %}

<section class="friend-view">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h1>{{friend.friend_name}}</h1>
            </div>
            <div class="col-xs-3">
                NPM
            </div>
            <div class="col-xs-9">
                : {{friend.npm}}
            </div>
            <div class="col-xs-3">
                Alamat   
            </div>
            <div class="col-xs-9">
                : <span id="address">{{friend.alamat_mhs}}</span>
            </div>
            <div class="col-xs-3">
                Tanggal lahir
            </div>
            <div class="col-xs-9">
                : {{friend.tgl_lahir}}
            </div>
            <div class="col-xs-3">
                Program Studi
            </div>
            <div class="col-xs-9">
                : {{friend.prodi}}
            </div>
            <div class="col-xs-3">
                Angkatan
            </div>
            <div class="col-xs-9">
                : {{friend.angkatan}}
            </div>
        </div>
    </div>
    <div class="container">
        <div id="googleMap" style="width:500px; height:400px; margin: 50px 0"></div>
    </div>
    <div>
    </div>
</section>
{% endblock %}
{% block script %}
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBnbJQq5rFmTEx43VzVmSLEu4UmPKYhkeI&callback=initMap" async defer>"</script>

<script>
    var address = $("#address").text();
    
    function initMap() {
        var geocoder = new google.maps.Geocoder();
        geocoder.geocode({'address': address}, function(results, status) {
            if (status === google.maps.GeocoderStatus.OK) {
                var propertiPeta = {
                    center: results[0].geometry.location,
                    zoom: 15,
                    mapTypeId: google.maps.MapTypeId.ROADMAP
                };
                var peta = new google.maps.Map(document.getElementById("googleMap"), propertiPeta);
                var marker = new google.maps.Marker({
                    map: peta,
                    position: results[0].geometry.location
                });
            } else {
                var html = '<div class="alert alert-danger text-center">\
                                Lokasi tidak ditemukan!\
                            </div>';
                $("#googleMap").append(html)
            }
        });
    }
</script>
{% endblock %}